apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage
  namespace: openchoreo-control-plane
spec:
  instances: 1
  enablePDB: false
  bootstrap:
    initdb:
      database: backstage
      owner: backstage
      secret:
        name: backstage
  managed:
    roles:
      - name: backstage
        ensure: present
        login: true
        createdb: true
        passwordSecret:
          name: backstage
  storage:
    size: 6Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
