apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage
  namespace: openchoreo-control-plane
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backstage
  data:
    - secretKey: postgres-user
      remoteRef:
        key: backstage/db
        property: username
    - secretKey: postgres-password
      remoteRef:
        key: backstage/db
        property: password
  dataFrom:
    - extract:
        key: backstage/db
    - extract:
        key: backstage/bootstrap
