resources:
  - fluxcd.yaml
  - cnpg.yaml
  - openchoreo-requirements.yaml
  - thunderid.yaml
  - openchoreo-control-plane.yaml
  - openchoreo-workflow-plane.yaml
  - openchoreo-observability-plane.yaml
  - opensearch-operator.yaml
  - observability-opensearch-users.yaml
  - openchoreo-observability-modules.yaml
  - openchoreo-resources.yaml
