apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openchoreo-resources
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: hestia
    namespace: flux-system
  path: ./openchoreo/fluxcd
  prune: true
  timeout: 5m
---
# Wildcard certificate for Openchoreo Gateway API
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: openchoreo-control-plane
spec:
  secretName: wildcard-tls
  dnsNames:
    - "*.platform.rpcu.lan"
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
