apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hestia
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 1m
  url: https://github.com/RPCU/hestia.git
  ref:
    branch: main
